### PR TITLE
do not merge - files sent by adyen

### PR DESCRIPTION
**Pull request by ralphiech**
hey @costash and @dominik-riha those are the files we received from adyen. from what i can see its the same as what we got, except a difference in the `package.json`, @dominik-riha is it save to say that we can keep 'our' version and dont need to merge this right?

### CODE REVIEW

**Comment by costash** [comment]
As I see it it's also changing from absolute to relative paths. We should probably merge the new changes in.

To be fair we should try to get rid of this dependency ASAP and either remove the code that needs it or make sure we use the new thing.

**Comment by dominik-riha** [comment]
agree. The logic doesn't seem to have changed so let's stick to our repo for the time being, but as quickly as possible implement our own thing.

**Comment by ralphiech** [comment]
Thanks for your thoughts @costash and @dominik-riha. There is no doubt that we need to get away from this code, I expect that this will never see the light of liveness :( meanwhile just wanted to be as update as possible but as the changes seem minimal if even existent I will keep this PR open for reference for now but don't merge

**Comment by costash** [comment]
This PR is obsolete by now.

**Pull request closed without merging**
